"""Provenance tracking (SourceFinder-style)."""

from typing import Dict, List, Optional, Set
from dataclasses import dataclass
from datetime import datetime


@dataclass
class Source:
    """A source of information."""
    source_id: str
    url: Optional[str] = None
    file_path: Optional[str] = None
    mission_id: Optional[str] = None
    timestamp: Optional[str] = None
    reliability_score: float = 1.0  # 0.0-1.0


class ProvenanceTracker:
    """Tracks the source and origin of all information.
    
    Enables queries like:
    - "What did I learn about X?"
    - "Where did I find that information?"
    - "Which sources contributed to this conclusion?"
    """

    def __init__(self):
        self._sources: Dict[str, Source] = {}
        self._document_sources: Dict[str, Set[str]] = {}  # doc_id -> source_ids

    def register_source(
        self,
        source_id: str,
        url: Optional[str] = None,
        file_path: Optional[str] = None,
        mission_id: Optional[str] = None,
    ) -> Source:
        """Register a new information source."""
        source = Source(
            source_id=source_id,
            url=url,
            file_path=file_path,
            mission_id=mission_id,
            timestamp=datetime.utcnow().isoformat(),
        )
        self._sources[source_id] = source
        return source

    def link_source_to_document(self, doc_id: str, source_id: str) -> None:
        """Link a document to one or more sources."""
        if doc_id not in self._document_sources:
            self._document_sources[doc_id] = set()
        self._document_sources[doc_id].add(source_id)

    def get_document_sources(self, doc_id: str) -> List[Source]:
        """Get all sources that contributed to a document."""
        source_ids = self._document_sources.get(doc_id, set())
        return [self._sources[sid] for sid in source_ids if sid in self._sources]

    def get_sources_by_url(self, url: str) -> List[Source]:
        """Find all sources from a specific URL."""
        return [s for s in self._sources.values() if s.url == url]

    def get_sources_by_mission(self, mission_id: str) -> List[Source]:
        """Find all sources generated by a mission."""
        return [s for s in self._sources.values() if s.mission_id == mission_id]
